import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '../ui/Navbar';
import Footer from '../ui/Footer';
import { ThemeProvider } from 'next-themes';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} mx-auto max-w-[128rem] bg-white antialiased dark:bg-neutral-950`}
      >
        <ThemeProvider defaultTheme="system" attribute="class" enableSystem>
          <Navbar />
          <div className="w-full px-4 sm:px-16 md:px-20 2xl:px-70">
            {children}
          </div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
