import {
  Introduction,
  Installtion,
  Button,
  Badge,
  ExpendableCard,
  Accordion,
  TabSelect,
  LogoCarousel,
  PointerCard,
  TiltCard,
  AnimatedButton,
  TextShimmer,
  AnimatedText,
  BentoGrid,
  Dialog,
} from '@/docs';

export const docsMap: Record<string, React.ComponentType> = {
  introduction: Introduction,
  installation: Installtion,
  button: Button,
  badge: Badge,
  'expendable-card': ExpendableCard,
  accordion: Accordion,
  'tab-select': TabSelect,
  'logo-carousel': LogoCarousel,
  'pointer-card': PointerCard,
  'tilt-card': TiltCard,
  'animated-button': AnimatedButton,
  'text-shimmer': TextShimmer,
  'animated-text': AnimatedText,
  'bento-grid': BentoGrid,
  dialog: Dialog,
};
